# Generated by Django 4.1 on 2022-09-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                default="", upload_to="", verbose_name="Photo profile"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("CREATOR", "creator"), ("SUSCRIBER", "susbcriber")],
                default="",
                max_length=30,
                verbose_name="Rôle",
            ),
            preserve_default=False,
        ),
    ]
