# Generated by Django 4.1 on 2022-09-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0002_user_profile_photo_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Photo profile"
            ),
        ),
    ]
