# Generated by Django 4.1 on 2022-09-17 00:09

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to=blog.models.user_photo_path),
        ),
    ]
